"""Initial migration.

Revision ID: 222502134f6a
Revises: 
Create Date: 2022-09-02 15:04:15.518339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222502134f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Unit_Of_Measure',
    sa.Column('Unit_Id', sa.Integer(), nullable=False),
    sa.Column('Unit_Description', sa.String(length=100), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Unit_Id')
    )
    op.create_table('customer_type',
    sa.Column('Cust_Type_Id', sa.Integer(), nullable=False),
    sa.Column('Type_Description', sa.String(length=100), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Cust_Type_Id')
    )
    op.create_table('hsn_details',
    sa.Column('HSN_Code', sa.Integer(), nullable=False),
    sa.Column('HSN_Description', sa.String(length=300), nullable=True),
    sa.Column('HSN_Percentage', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('HSN_Code')
    )
    op.create_table('inventory_status',
    sa.Column('Status_Id', sa.Integer(), nullable=False),
    sa.Column('Status_Description', sa.String(length=100), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Status_Id')
    )
    op.create_table('request_status',
    sa.Column('Status_Id', sa.Integer(), nullable=False),
    sa.Column('Status_Description', sa.String(length=100), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Status_Id')
    )
    op.create_table('system_authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Role', sa.String(length=50), nullable=True),
    sa.Column('Users', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('firstname', sa.String(length=300), nullable=True),
    sa.Column('lastname', sa.String(length=300), nullable=True),
    sa.Column('username', sa.String(length=300), nullable=True),
    sa.Column('firstTimeLogin', sa.Boolean(), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer_details',
    sa.Column('Customer_ID', sa.Integer(), nullable=False),
    sa.Column('Customer_Type_Id', sa.Integer(), nullable=True),
    sa.Column('Customer_Name', sa.String(length=300), nullable=True),
    sa.Column('Customer_Email', sa.String(length=300), nullable=True),
    sa.Column('Customer_Mobile_No', sa.String(length=300), nullable=True),
    sa.Column('Customer_GST_No', sa.String(length=300), nullable=True),
    sa.Column('Customer_Bank_Name', sa.String(length=300), nullable=True),
    sa.Column('Customer_Bank_Branch', sa.String(length=300), nullable=True),
    sa.Column('Customer_Account_No', sa.String(length=300), nullable=True),
    sa.Column('Customer_IFSC_Code', sa.String(length=300), nullable=True),
    sa.Column('Customer_Address', sa.String(length=400), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_Type_Id'], ['customer_type.Cust_Type_Id'], ),
    sa.PrimaryKeyConstraint('Customer_ID'),
    sa.UniqueConstraint('Customer_Email')
    )
    op.create_table('expense_master',
    sa.Column('Expense_Req_Id', sa.Integer(), nullable=False),
    sa.Column('Request_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Request_Status_Id'], ['request_status.Status_Id'], ),
    sa.PrimaryKeyConstraint('Expense_Req_Id')
    )
    op.create_table('item_master',
    sa.Column('Item_Code', sa.Integer(), nullable=False),
    sa.Column('HSN_Code', sa.Integer(), nullable=True),
    sa.Column('Item_Description', sa.String(length=300), nullable=True),
    sa.Column('Rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HSN_Code'], ['hsn_details.HSN_Code'], ),
    sa.PrimaryKeyConstraint('Item_Code')
    )
    op.create_table('expense_attachments',
    sa.Column('Attachment_Id', sa.Integer(), nullable=False),
    sa.Column('Attachment_Name', sa.String(length=300), nullable=True),
    sa.Column('File_Content', sa.LargeBinary(), nullable=True),
    sa.Column('Expense_Req_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Expense_Req_Id'], ['expense_master.Expense_Req_Id'], ),
    sa.PrimaryKeyConstraint('Attachment_Id')
    )
    op.create_table('expense_detail',
    sa.Column('Expense_Det_Id', sa.Integer(), nullable=False),
    sa.Column('Expense_Req_Id', sa.Integer(), nullable=True),
    sa.Column('Expense_Description', sa.String(length=500), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Expense_Req_Id'], ['expense_master.Expense_Req_Id'], ),
    sa.PrimaryKeyConstraint('Expense_Det_Id')
    )
    op.create_table('inventory',
    sa.Column('Inventory_Code', sa.Integer(), nullable=False),
    sa.Column('HSN_Code', sa.Integer(), nullable=True),
    sa.Column('Item_Code', sa.Integer(), nullable=True),
    sa.Column('Rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Units_Of_Measurement', sa.Integer(), nullable=True),
    sa.Column('Item_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HSN_Code'], ['hsn_details.HSN_Code'], ),
    sa.ForeignKeyConstraint(['Item_Code'], ['item_master.Item_Code'], ),
    sa.ForeignKeyConstraint(['Item_Status_Id'], ['inventory_status.Status_Id'], ),
    sa.ForeignKeyConstraint(['Units_Of_Measurement'], ['Unit_Of_Measure.Unit_Id'], ),
    sa.PrimaryKeyConstraint('Inventory_Code'),
    sa.UniqueConstraint('Item_Code')
    )
    op.create_table('payments_received',
    sa.Column('Payment_Req_Id', sa.Integer(), nullable=False),
    sa.Column('Customer_Id', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Payment_Details', sa.String(length=500), nullable=True),
    sa.Column('Request_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_Id'], ['customer_details.Customer_ID'], ),
    sa.ForeignKeyConstraint(['Request_Status_Id'], ['request_status.Status_Id'], ),
    sa.PrimaryKeyConstraint('Payment_Req_Id')
    )
    op.create_table('purchase_master',
    sa.Column('Purchase_Req_Id', sa.Integer(), nullable=False),
    sa.Column('Invoice_No', sa.String(length=100), nullable=True),
    sa.Column('Customer_Id', sa.Integer(), nullable=True),
    sa.Column('Commission', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Request_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_Id'], ['customer_details.Customer_ID'], ),
    sa.ForeignKeyConstraint(['Request_Status_Id'], ['request_status.Status_Id'], ),
    sa.PrimaryKeyConstraint('Purchase_Req_Id'),
    sa.UniqueConstraint('Invoice_No')
    )
    op.create_table('sales_master',
    sa.Column('Sales_Req_Id', sa.Integer(), nullable=False),
    sa.Column('Customer_Id', sa.Integer(), nullable=True),
    sa.Column('Request_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_Id'], ['customer_details.Customer_ID'], ),
    sa.ForeignKeyConstraint(['Request_Status_Id'], ['request_status.Status_Id'], ),
    sa.PrimaryKeyConstraint('Sales_Req_Id')
    )
    op.create_table('attachments',
    sa.Column('Attachment_Id', sa.Integer(), nullable=False),
    sa.Column('Attachment_Name', sa.String(length=300), nullable=True),
    sa.Column('File_Content', sa.LargeBinary(), nullable=True),
    sa.Column('Purchase_Req_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Purchase_Req_Id'], ['purchase_master.Purchase_Req_Id'], ),
    sa.PrimaryKeyConstraint('Attachment_Id')
    )
    op.create_table('inventory_details',
    sa.Column('Inventory_Det_Code', sa.Integer(), nullable=False),
    sa.Column('Inventory_Code', sa.Integer(), nullable=True),
    sa.Column('HSN_Code', sa.Integer(), nullable=True),
    sa.Column('Item_Code', sa.Integer(), nullable=True),
    sa.Column('Rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Units_Of_Measurement', sa.Integer(), nullable=True),
    sa.Column('Item_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HSN_Code'], ['hsn_details.HSN_Code'], ),
    sa.ForeignKeyConstraint(['Inventory_Code'], ['inventory.Inventory_Code'], ),
    sa.ForeignKeyConstraint(['Item_Code'], ['item_master.Item_Code'], ),
    sa.ForeignKeyConstraint(['Item_Status_Id'], ['inventory_status.Status_Id'], ),
    sa.ForeignKeyConstraint(['Units_Of_Measurement'], ['Unit_Of_Measure.Unit_Id'], ),
    sa.PrimaryKeyConstraint('Inventory_Det_Code')
    )
    op.create_table('payment_attachments',
    sa.Column('Attachment_Id', sa.Integer(), nullable=False),
    sa.Column('Attachment_Name', sa.String(length=300), nullable=True),
    sa.Column('File_Content', sa.LargeBinary(), nullable=True),
    sa.Column('Payment_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Payment_Id'], ['payments_received.Payment_Req_Id'], ),
    sa.PrimaryKeyConstraint('Attachment_Id')
    )
    op.create_table('purchase_detail',
    sa.Column('Purchase_Det_Id', sa.Integer(), nullable=False),
    sa.Column('Purchase_Req_Id', sa.Integer(), nullable=True),
    sa.Column('Item_Code', sa.Integer(), nullable=True),
    sa.Column('HSN_Code', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('GST_Percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Units_Of_Measurement', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HSN_Code'], ['hsn_details.HSN_Code'], ),
    sa.ForeignKeyConstraint(['Item_Code'], ['item_master.Item_Code'], ),
    sa.ForeignKeyConstraint(['Purchase_Req_Id'], ['purchase_master.Purchase_Req_Id'], ),
    sa.ForeignKeyConstraint(['Units_Of_Measurement'], ['Unit_Of_Measure.Unit_Id'], ),
    sa.PrimaryKeyConstraint('Purchase_Det_Id')
    )
    op.create_table('sales_attachments',
    sa.Column('Attachment_Id', sa.Integer(), nullable=False),
    sa.Column('Attachment_Name', sa.String(length=300), nullable=True),
    sa.Column('File_Content', sa.LargeBinary(), nullable=True),
    sa.Column('Sales_Req_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=300), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Sales_Req_Id'], ['sales_master.Sales_Req_Id'], ),
    sa.PrimaryKeyConstraint('Attachment_Id')
    )
    op.create_table('sales_detail',
    sa.Column('Sales_Det_Id', sa.Integer(), nullable=False),
    sa.Column('Sales_Req_Id', sa.Integer(), nullable=True),
    sa.Column('Item_Code', sa.Integer(), nullable=True),
    sa.Column('HSN_Code', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('GST_Percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Units_Of_Measurement', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HSN_Code'], ['hsn_details.HSN_Code'], ),
    sa.ForeignKeyConstraint(['Item_Code'], ['item_master.Item_Code'], ),
    sa.ForeignKeyConstraint(['Sales_Req_Id'], ['sales_master.Sales_Req_Id'], ),
    sa.ForeignKeyConstraint(['Units_Of_Measurement'], ['Unit_Of_Measure.Unit_Id'], ),
    sa.PrimaryKeyConstraint('Sales_Det_Id')
    )
    op.create_table('invested_capital',
    sa.Column('Invest_Req_Id', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Investment_Details', sa.String(length=500), nullable=True),
    sa.Column('Attachment_Id', sa.Integer(), nullable=True),
    sa.Column('Request_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Attachment_Id'], ['attachments.Attachment_Id'], ),
    sa.ForeignKeyConstraint(['Request_Status_Id'], ['request_status.Status_Id'], ),
    sa.PrimaryKeyConstraint('Invest_Req_Id')
    )
    op.create_table('payments_given',
    sa.Column('Payment_Req_Id', sa.Integer(), nullable=False),
    sa.Column('Customer_Id', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('Payment_Details', sa.String(length=500), nullable=True),
    sa.Column('Attachment_Id', sa.Integer(), nullable=True),
    sa.Column('Request_Status_Id', sa.Integer(), nullable=True),
    sa.Column('Comments', sa.String(length=500), nullable=True),
    sa.Column('Created_By', sa.String(length=300), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_by', sa.String(length=300), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Attachment_Id'], ['attachments.Attachment_Id'], ),
    sa.ForeignKeyConstraint(['Customer_Id'], ['customer_details.Customer_ID'], ),
    sa.ForeignKeyConstraint(['Request_Status_Id'], ['request_status.Status_Id'], ),
    sa.PrimaryKeyConstraint('Payment_Req_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_given')
    op.drop_table('invested_capital')
    op.drop_table('sales_detail')
    op.drop_table('sales_attachments')
    op.drop_table('purchase_detail')
    op.drop_table('payment_attachments')
    op.drop_table('inventory_details')
    op.drop_table('attachments')
    op.drop_table('sales_master')
    op.drop_table('purchase_master')
    op.drop_table('payments_received')
    op.drop_table('inventory')
    op.drop_table('expense_detail')
    op.drop_table('expense_attachments')
    op.drop_table('item_master')
    op.drop_table('expense_master')
    op.drop_table('customer_details')
    op.drop_table('user')
    op.drop_table('system_settings')
    op.drop_table('system_readings')
    op.drop_table('system_authorization')
    op.drop_table('request_status')
    op.drop_table('inventory_status')
    op.drop_table('hsn_details')
    op.drop_table('customer_type')
    op.drop_table('Unit_Of_Measure')
    # ### end Alembic commands ###
